// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package api

// Defines values for PatchDocumentOp.
const (
	PatchDocumentOpAdd PatchDocumentOp = "add"

	PatchDocumentOpCopy PatchDocumentOp = "copy"

	PatchDocumentOpMove PatchDocumentOp = "move"

	PatchDocumentOpRemove PatchDocumentOp = "remove"

	PatchDocumentOpReplace PatchDocumentOp = "replace"

	PatchDocumentOpTest PatchDocumentOp = "test"
)

// The created time of this record
type Created string

// Email defines model for Email.
type Email string

// The last modified time of this record
type LastModified string

// A JSONPatch document as defined by RFC 6902
type PatchDocument struct {
	// A string containing a JSON Pointer value.
	From *string `json:"from,omitempty"`

	// The operation to be performed
	Op PatchDocumentOp `json:"op"`

	// A JSON-Pointer
	Path string `json:"path"`

	// The value to be used within the operations.
	Value *map[string]interface{} `json:"value,omitempty"`
}

// The operation to be performed
type PatchDocumentOp string

// A 27 character string representing an unique id
type StringId string

// SystemTags defines model for SystemTags.
type SystemTags []string

// User defines model for User.
type User struct {
	CommonAccess string     `binding:"required,oneof=private public" json:"commonAccess"`
	Email        Email      `binding:"required,email,min=1,max=512" json:"email"`
	Name         string     `binding:"required,min=1,max=512" json:"name"`
	SystemTags   SystemTags `binding:"required,max=64,dive,max=256" json:"systemTags"`
	UserTags     UserTags   `binding:"required,max=64,dive,max=256" json:"userTags"`
}

// UserGet defines model for UserGet.
type UserGet struct {
	// Embedded struct due to allOf(#/components/schemas/User)
	User `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// The created time of this record
	Created Created `json:"created"`
	UserId  int64   `json:"userId"`
	Version int64   `json:"version"`
}

// UserTags defines model for UserTags.
type UserTags []string

// UserId defines model for UserId.
type UserId int64

// UserGetOk defines model for UserGetOk.
type UserGetOk UserGet

// UserPostOk defines model for UserPostOk.
type UserPostOk struct {
	UserId  int64 `json:"userId"`
	Version int64 `json:"version"`
}

// A JSONPatch document as defined by RFC 6902
type Patch PatchDocument

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody User

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody

// PatchUsersUserIdJSONRequestBody defines body for PatchUsersUserId for application/json ContentType.
type PatchUsersUserIdJSONRequestBody Patch
