// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package api

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Email defines model for Email.
type Email openapi_types.Email

// The last modified time of this record
type LastModified string

// A 27 character string representing an unique id
type StringId string

// SystemTags defines model for SystemTags.
type SystemTags []string

// User defines model for User.
type User struct {
	Email      Email      `json:"email"`
	Name       string     `json:"name" validate:"required,min=1,max=512"`
	SystemTags SystemTags `json:"systemTags"`
	UserTags   UserTags   `json:"userTags" ts:",no-null"`
}

// UserGet defines model for UserGet.
type UserGet struct {
	// Embedded struct due to allOf(#/components/schemas/User)
	User `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// The last modified time of this record
	LastModified LastModified `json:"lastModified"`

	// A 27 character string representing an unique id
	UserId StringId `json:"userId"`
}

// UserPatch defines model for UserPatch.
type UserPatch struct {
	// Embedded struct due to allOf(#/components/schemas/User)
	User `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// A 27 character string representing an unique id
	UserId StringId `json:"userId"`
}

// UserTags defines model for UserTags.
type UserTags []string

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody User

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody
