stages:
  - release

release:
  stage: release
  image: docker:stable
  services:
    - name: docker:dind
      alias: docker

  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
    GITLAB_TOKEN: $GITLAB_TOKEN

    DOCKER_DRIVER: overlay2
    # https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
    DOCKER_TLS_CERTDIR: "/certs"

  # # Only run this release job for tags, not every commit (for example).
  # only:
  #   refs:
  #     - tags

  script: |
    # GITLAB_TOKEN is needed to create GitLab releases.
    # DOCKER_* are needed to push Docker images.
    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/bardview5/bardview5 \
      -w /go/src/gitlab.com/bardview5/bardview5 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      goreleaser/goreleaser release --rm-dist
