// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package access

import (
	"context"

	"github.com/lib/pq"
)

const getUser = `-- name: GetUser :one
SELECT id, uid, created_by, created_at, effective_date, end_date, is_active, email, name, tags FROM public."user" LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EffectiveDate,
		&i.EndDate,
		&i.IsActive,
		&i.Email,
		&i.Name,
		pq.Array(&i.Tags),
	)
	return i, err
}
