# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bardview5
    ports:
      - "5432:5432"
    volumes:
      - ./snapshot:/sql_dump

  kratos-migrate:
    image: oryd/kratos:v0.8.0-alpha.3-sqlite
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
      - ./kratos-sqlite:/var/lib/sqlite
    command: -c /etc/config/kratos/kratos.yml migrate -e --yes sql
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.8.0-alpha.3-sqlite
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - ./kratos-sqlite:/var/lib/sqlite
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

networks:
  intranet: