# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bardview5
    ports:
      - "5432:5432"
    volumes:
      - ./snapshot:/sql_dump
