// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package models

type RPGResponseType struct {
	Data   RPG                    `json:"data"`
	Errors map[string]interface{} `json:"errors"`
}

type RPGListResponseType struct {
	Data   RPGList                `json:"data"`
	Errors map[string]interface{} `json:"errors"`
}
