// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CommonAccess struct {
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
}

type Dnd5eLanguage struct {
	Dnd5eLanguageID int64         `db:"dnd5e_language_id"`
	CreatedBy       sql.NullInt64 `db:"created_by"`
	CreatedAt       time.Time     `db:"created_at"`
	Version         int64         `db:"version"`
	Name            string        `db:"name"`
}

type Dnd5eMonster struct {
	Dnd5eMonsterID       int64          `db:"dnd5e_monster_id"`
	CreatedBy            sql.NullInt64  `db:"created_by"`
	CreatedAt            time.Time      `db:"created_at"`
	Version              int64          `db:"version"`
	Dnd5eSettingID       int64          `db:"dnd5e_setting_id"`
	Name                 string         `db:"name"`
	Sources              []string       `db:"sources"`
	UserTags             []string       `db:"user_tags"`
	Languages            []string       `db:"languages"`
	Environments         []string       `db:"environments"`
	IsLegendary          bool           `db:"is_legendary"`
	IsUnique             bool           `db:"is_unique"`
	MonsterType          sql.NullString `db:"monster_type"`
	Alignment            sql.NullString `db:"alignment"`
	SizeCategory         sql.NullString `db:"size_category"`
	MilliChallengeRating sql.NullInt64  `db:"milli_challenge_rating"`
	ArmorClass           sql.NullInt32  `db:"armor_class"`
	HitPoints            sql.NullInt32  `db:"hit_points"`
	Description          sql.NullString `db:"description"`
	StrScore             sql.NullInt32  `db:"str_score"`
	DexScore             sql.NullInt32  `db:"dex_score"`
	IntScore             sql.NullInt32  `db:"int_score"`
	WisScore             sql.NullInt32  `db:"wis_score"`
	ConScore             sql.NullInt32  `db:"con_score"`
	ChaScore             sql.NullInt32  `db:"cha_score"`
}

type Dnd5eMonsterType struct {
	CreatedBy sql.NullInt64 `db:"created_by"`
	CreatedAt time.Time     `db:"created_at"`
	Version   int64         `db:"version"`
	Name      string        `db:"name"`
}

type Dnd5eSetting struct {
	Dnd5eSettingID int64          `db:"dnd5e_setting_id"`
	CreatedBy      sql.NullInt64  `db:"created_by"`
	CreatedAt      time.Time      `db:"created_at"`
	Version        int64          `db:"version"`
	IsActive       bool           `db:"is_active"`
	CommonAccess   string         `db:"common_access"`
	UserTags       []string       `db:"user_tags"`
	SystemTags     []string       `db:"system_tags"`
	Name           string         `db:"name"`
	Module         sql.NullString `db:"module"`
	Description    string         `db:"description"`
}

type Dnd5eSettingAssignment struct {
	CreatedBy      sql.NullInt64 `db:"created_by"`
	CreatedAt      time.Time     `db:"created_at"`
	Version        int64         `db:"version"`
	UserID         int64         `db:"user_id"`
	Dnd5eSettingID int64         `db:"dnd5e_setting_id"`
	RoleAction     string        `db:"role_action"`
}

type Dnd5eSizeCategory struct {
	CreatedBy sql.NullInt64 `db:"created_by"`
	CreatedAt time.Time     `db:"created_at"`
	Version   int64         `db:"version"`
	Name      string        `db:"name"`
	Space     string        `db:"space"`
}

type RoleAction struct {
	Name        string    `db:"name"`
	RoleSubject string    `db:"role_subject"`
	CreatedAt   time.Time `db:"created_at"`
}

type RoleSubject struct {
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
}

type SchemaMigration struct {
	Version int64 `db:"version"`
	Dirty   bool  `db:"dirty"`
}

type User struct {
	UserID        int64         `db:"user_id"`
	Uuid          uuid.UUID     `db:"uuid"`
	CreatedBy     sql.NullInt64 `db:"created_by"`
	CreatedAt     time.Time     `db:"created_at"`
	Version       int64         `db:"version"`
	EffectiveDate time.Time     `db:"effective_date"`
	EndDate       sql.NullTime  `db:"end_date"`
	IsActive      bool          `db:"is_active"`
	CommonAccess  string        `db:"common_access"`
	Email         string        `db:"email"`
	Name          string        `db:"name"`
	UserTags      []string      `db:"user_tags"`
	SystemTags    []string      `db:"system_tags"`
}
