// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type CommonAccess struct {
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
}

type Role struct {
	RoleID        int64         `db:"role_id"`
	CreatedBy     sql.NullInt64 `db:"created_by"`
	CreatedAt     time.Time     `db:"created_at"`
	EffectiveDate time.Time     `db:"effective_date"`
	EndDate       sql.NullTime  `db:"end_date"`
	IsActive      bool          `db:"is_active"`
	Name          string        `db:"name"`
	RoleTypeID    sql.NullInt64 `db:"role_type_id"`
	Tags          []string      `db:"tags"`
}

type RoleAction struct {
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
}

type RoleAssignment struct {
	RoleAssignmentID int64         `db:"role_assignment_id"`
	CreatedBy        sql.NullInt64 `db:"created_by"`
	CreatedAt        time.Time     `db:"created_at"`
	EffectiveDate    time.Time     `db:"effective_date"`
	EndDate          sql.NullTime  `db:"end_date"`
	IsActive         bool          `db:"is_active"`
	RoleID           int64         `db:"role_id"`
	UserID           int64         `db:"user_id"`
	Tags             []string      `db:"tags"`
}

type RolePermission struct {
	RolePermissionID int64           `db:"role_permission_id"`
	CreatedBy        sql.NullInt64   `db:"created_by"`
	CreatedAt        time.Time       `db:"created_at"`
	EffectiveDate    time.Time       `db:"effective_date"`
	EndDate          sql.NullTime    `db:"end_date"`
	IsActive         bool            `db:"is_active"`
	RoleID           int64           `db:"role_id"`
	Action           string          `db:"action"`
	Subject          string          `db:"subject"`
	SubjectID        sql.NullInt64   `db:"subject_id"`
	Conditions       json.RawMessage `db:"conditions"`
	Fields           []string        `db:"fields"`
}

type RoleSubject struct {
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
}

type RoleType struct {
	RoleTypeID                 int64     `db:"role_type_id"`
	CreatedAt                  time.Time `db:"created_at"`
	Name                       string    `db:"name"`
	MultipleAssignmentsAllowed bool      `db:"multiple_assignments_allowed"`
	SystemManaged              bool      `db:"system_managed"`
}

type SchemaMigration struct {
	Version int64 `db:"version"`
	Dirty   bool  `db:"dirty"`
}

type User struct {
	UserID        int64         `db:"user_id"`
	Uuid          uuid.UUID     `db:"uuid"`
	CreatedBy     sql.NullInt64 `db:"created_by"`
	CreatedAt     time.Time     `db:"created_at"`
	Version       int64         `db:"version"`
	EffectiveDate time.Time     `db:"effective_date"`
	EndDate       sql.NullTime  `db:"end_date"`
	IsActive      bool          `db:"is_active"`
	CommonAccess  string        `db:"common_access"`
	Email         string        `db:"email"`
	Name          string        `db:"name"`
	UserTags      []string      `db:"user_tags"`
	SystemTags    []string      `db:"system_tags"`
}
