// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	GetAcl(ctx context.Context, arg GetAclParams) ([]GetAclRow, error)
	UserInsert(ctx context.Context, arg UserInsertParams) (int64, error)
	UsersFindByUid(ctx context.Context, arg UsersFindByUidParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
