on: [push, pull_request]
name: Test
jobs:
  client:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - run: npm install
      working-directory: bv5-app
    - run: npm run generate
      working-directory: bv5-app
    - run: npm run test
      working-directory: bv5-app
    - run: npm run build
      working-directory: bv5-app
    - uses: actions/upload-artifact@v2
      with:
        name: client-${{ matrix.os }}
        path: bv5-app/public/
      if: github.event_name != 'pull_request'
  server:
    # env:
    #   GOPROXY: https://proxy.golang.org
      # GO111MODULE: on
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Mage
      run: go get github.com/magefile/mage@07afc7d24f4d6d6442305d49552f04fbda5ccb3e
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - if: matrix.os == 'ubuntu-latest'
      name: Test Ubuntu
      working-directory: server
      env: 
        BARDVIEW5EXE: bardview
      run: |
        mage -v all
    - uses: actions/upload-artifact@v2
      with:
        name: server-${{ matrix.os }}
        path: server/build/
      if: github.event_name != 'pull_request'